language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --version && echo && vendor/bin/phpcs -p --standard=PSR2 src tests
